services:
  node:
    image: node:18
    container_name: spraby-api-node
    working_dir: /var/www/html
    volumes:
        - ./:/var/www/html
        - node_modules:/var/www/html/node_modules
    command: sh -c "npm install && npm run dev"

  app:
    environment:
      - WWWUSER=1000
      - WWWGROUP=1000
    build:
      context: .
      dockerfile: .docker/php/Dockerfile
      args:
          WWWUSER: ${WWWUSER}
          WWWGROUP: ${WWWGROUP}
    container_name: spraby-api
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres

  nginx:
    image: nginx:stable
    container_name: spraby-api-nginx
    ports:
      - "8000:80"
    volumes:
      - ./:/var/www/html
      - ./.docker/nginx:/etc/nginx/conf.d
    depends_on:
      - app

  postgres:
    image: postgres:15
    container_name: spraby-api-postgres
    ports:
      - "5435:5432"
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
  node_modules:
